version: 2
conda:
  environment: doc/environment.yml
build:
  os: ubuntu-lts-latest
  tools:
    python: "mambaforge-latest"
python:
  install:
    - method: setuptools
      path: .
sphinx:
  configuration: docs/conf.py