

VERBOSE: No

# Two diagnostics, based on SLA (e.g., Chelton et al, 2011)
# or the Q-parameter (e.g., Kurian et al, 2011) are available
DIAGNOSTIC_TYPE: 'SLA'
#DIAGNOSTIC_TYPE: 'Q' # not yet implemented

# Specify the AVISO domain
DOMAIN:
  THE_DOMAIN: 'Global'
#   THE_DOMAIN: 'Regional'
  #THE_DOMAIN = 'BlackSea'
  #THE_DOMAIN = 'MedSea' # not yet implemented
  LONMIN: -40.
  LONMAX: -30.
  LATMIN: 20.
  LATMAX: 30.
  DATE_STR: 20020101
  DATE_END: 20020630

# Specify the AVISO product
AVISO:
  AVISO_DT14: Yes # Use new AVISO DT14 data (e.g., Capet et al, 2014)
  AVISO_FILES: 'dt_global_twosat_msla_h_????????_20140106.nc'
  #AVISO_FILES: 'dt_ref_global_merged_msla_h_qd_????????_????????_????????.nc'
  AVISO_DT14_SUBSAMP: No # subsample the daily AVISO DT14
  DAYS_BTWN_RECORDS: 7  # sampling rate (days)

PATHS:
  # Path to AVISO data
  DATA_DIR: '/data/PVA/Externe/global/delayed-time/grids/msla/two-sat-merged/h/2002/'
#   DATA_DIR: '/Users/emason/data/AVISO/global/delayed-time/grids/msla/all-sat-merged/h/'
  #DATA_DIR: '/marula/emason/data/altimetry/global/delayed-time/grids/msla/two-sat-merged/h/'
  # Path and filename of Chelton et al (1998) Rossby radius data
  # Obtain file from:
  # http://www-po.coas.oregonstate.edu/research/po/research/rossby_radius/
  RW_PATH: '/homelocal/emason/rossrad.dat'
#   RW_PATH: '/Users/emason/Downloads/rossrad.dat'
  #RW_PATH: '/home/emason/data_tmp/chelton_eddies/rossrad.dat'

  # Path for saving of outputs
#   SAVE_DIR: '/homelocal/emason/outputs/before_swirl/'
#   SAVE_DIR: '/homelocal/emason/outputs/after_swirl/'
#   SAVE_DIR: '/homelocal/emason/outputs/after_swirl_slice/'
  SAVE_DIR: '/homelocal/emason/outputs/'
#   SAVE_DIR: '/Users/emason/toto/'
  #SAVE_DIR: '/marula/emason/aviso_eddy_tracking/fd0cdb4b2bd9/'

  # Reference Julian day (Julian date at Jan 1, 1992)
JDAY_REFERENCE: 2448623.

# Define contouring parameters
CONTOUR_PARAMETER:
  # Set Q contour spacing 
  CONTOUR_PARAMETER_Q:
    MAX_Q: 5*10**-11
    NUM_LEVS: 100
  # Set SLA contour spacing (cm)
  CONTOUR_PARAMETER_SLA:
    MAX_SLA: 100.
    INTERVAL: 0.25

# Shape error (see Kurian et al 2011)
SHAPE_ERROR: 55. # % (Mason et al 2014 use 55%)
    
# Filtering
SMOOTHING: Yes
SMOOTHING_SLA:
  TYPE: 'Gaussian'
  ZWL: 20. # degrees, zonal wavelength (see Chelton etal 2011)
  MWL: 10. # degrees, meridional wavelength

SMOOTHING_Q:
  TYPE: 'Hanning'
  SMOOTH_FAC: 5 # number of passes

# Min and max permitted eddy radii [degrees] and amplitudes (cm)
RADMIN: 0.35 # 0.4 for DT10, 0.35 for DT14
RADMAX: 4.461
AMPMIN: 1.
AMPMAX: 150.

TRACK_DURATION_MIN: 28 # days
  
SEPARATION_METHOD: 'ellipse'
#SEPARATION_METHOD: 'sum_radii'

# MPM14 use 1; CSS11 have no limit
MAX_LOCAL_EXTREMA: 1


# Typical parameters
DIST0: 25000. # m separation distance after ~7 days (see CSS11 fig 22)
RAD0: 60000. # m
AMP0: 2. # cm
TEMP0: 15.
SALT0: 35.


# Parameters used by Chelton etal and Kurian etal (Sec. 3.2) to ensure 
# the slow evolution of the eddies over time;
# they use min and max values of 0.25 and 2.5
EVOLVE_AMP_MIN: 0.0005 # min change in amplitude
EVOLVE_AMP_MAX: 500 # max change in amplitude
EVOLVE_AREA_MIN: 0.0005 # min change in area
EVOLVE_AREA_MAX: 500 # max change in area


# Make figures for animations
SAVE_FIGURES: No


# Define track_extra_variables to track and save:
# - effective contour points
# - speed-based contour points
# - shape test values
# - profiles of swirl velocity from effective contour inwards
# Useful for working with ARGO data    
TRACK_EXTRA_VARIABLES: No

# 'RectBivariate' is faster
INTERP_METHOD: 'RectBivariate'
#INTERP_METHOD: 'griddata'
    
    
    