#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
Do grid filtering
"""
from py_eddy_tracker import EddyParser
from py_eddy_tracker.dataset.grid import RegularGridDataset


def id_parser():
    parser = EddyParser('Eddy Identification')
    parser.add_argument('filename')
    parser.add_argument('grid')
    parser.add_argument('longitude')
    parser.add_argument('latitude')
    parser.add_argument('filename_out')
    parser.add_argument('--cut_wavelength', default=500, type=float,
                        help='Wavelength for mesoscale filter in km')
    parser.add_argument('--filter_order', default=3, type=int)
    parser.add_argument('--low', action='store_true')
    parser.add_argument('--extend', default=0, type=float,
                        help='Keep pixel compute by filtering on mask')
    return parser


if __name__ == '__main__':
    args = id_parser().parse_args()

    h = RegularGridDataset(args.filename, args.longitude, args.latitude)
    if args.low:
        h.bessel_low_filter(args.grid, args.cut_wavelength, order=args.filter_order, extend=args.extend)
    else:
        h.bessel_high_filter(args.grid, args.cut_wavelength, order=args.filter_order, extend=args.extend)
    h.write(args.filename_out)
