#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
Gui for eddy atlas
"""
from argparse import ArgumentParser
from py_eddy_tracker.observations.tracking import TrackEddiesObservations
from py_eddy_tracker.gui import GUI


def parser():
    parser = ArgumentParser("Eddy atlas GUI")
    parser.add_argument("atlas", nargs="+")
    parser.add_argument("--med", action='store_true')
    return parser.parse_args()


if __name__ == "__main__":
    args = parser()
    atlas = {
        dataset: TrackEddiesObservations.load_file(dataset) for dataset in args.atlas
    }
    g = GUI(**atlas)
    if args.med:
        g.med()
    g.show()
