channels:
  - conda-forge
dependencies:
  - python>=3.10 <3.13
  - ffmpeg
  - pip
  - pip:
    - -r ../requirements.txt
    - sphinx-gallery
    - sphinx_rtd_theme
    - sphinx>=3.1
    - pyeddytrackersample
