channels:
  - conda-forge
dependencies:
  - python>=3.10, <3.13
  - ffmpeg
  - pip
  - pip:
    - -r ../requirements.txt
    - git+https://github.com/AntSimi/py-eddy-tracker-sample-id.git
    - sphinx-gallery
    - sphinx_rtd_theme
    - sphinx>=3.1
    - pyeddytrackersample
